services:
    db:
        image: postgres
        restart: always
        ports:
            - "${DB_PORT:-5434}:5432"
        environment:
            - POSTGRES_PASSWORD=pepito1234
            - POSTGRES_DB=fastapi
        volumes:
            - postgres-volume:/var/lib/postgresql/data

    api:
        depends_on:
            - db
        build: .
        restart: always
        ports:
            - "${API_PORT:-9001}:9000"
        volumes:
            - ./:/usr/src/app
        env_file:
            - ./.env
        environment:
            - DATABASE_HOSTNAME=db
            - DATABASE_PORT=5432
            - DATABASE_PASSWORD=pepito1234
            - DATABASE_NAME=fastapi
            - DATABASE_USERNAME=postgres
        command: |
            sh -c "
                echo 'Waiting for database...' &&
                while ! pg_isready -h db -p 5432 -U postgres; do sleep 2; done &&
                echo 'Database ready, running migrations...' &&
                alembic upgrade elo_ranking_system &&
                alembic upgrade add_categories &&
                python -c 'import sys; sys.path.append(\"/usr/src/app\"); from app.database import SessionLocal; from app.models import Category; db = SessionLocal(); categories = [{\"name\": \"paintings\", \"description\": \"Paintings and artwork\"}, {\"name\": \"historical-photos\", \"description\": \"Historical photographs\"}, {\"name\": \"memes\", \"description\": \"Internet memes and humorous content\"}, {\"name\": \"anything\", \"description\": \"Anything else\"}]; [db.add(Category(**cat)) for cat in categories if not db.query(Category).filter(Category.name == cat[\"name\"]).first()]; db.commit(); db.close(); print(\"Categories initialized\")' &&
                python import_r2_photos.py &&
                uvicorn app.main:app --host 0.0.0.0 --port 9000 --reload
            "

volumes:
    postgres-volume:
