services:
  - type: web
    name: photorank
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: photorank-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: CORS_ORIGINS
        value: "*"
      - key: FRONTEND_URL
        value: "https://photorank-00e51b.onrender.com"
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: photorank-db
    databaseName: photorank
    user: photorank
    plan: starter